spring.application.name=microservicio
server.port=8080

# AWS S3 Configuration
aws.s3.bucket-name=inscripciones-akatsuki
aws.region=us-east-1
aws.access-key-id=${AWS_ACCESS_KEY_ID}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}
